import React from 'react';
import Head from "next/head";
import Navbar from "@/app/components/Navbar";
import Hero from "@/app/components/Hero";
import Catalog from "@/app/components/Catalog";
import Services from "@/app/components/Services";
import Footer from "@/app/components/Footer";
import {Product} from "@/app/type";

function Home({products}: { products: Product[] }) {
    return (
        <>
            <Head>
                <title>FoodStiks</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/app/favicon.ico"/>
            </Head>
            <main className='bg-yellow-200'>
                <div>
                    <Navbar/>
                    <Hero/>
                    <div className='bg-red-600'>
                        <h1 className='text-center text-5xl text-white p-8 uppercase font-bold '>Confira nosso
                            cardápio!</h1>
                        <div className='grid grid-cols-3 gap-5 '>
                            {products.map(product => <Catalog product={product} key={product.id}/>)}
                        </div>
                    </div>
                </div>
                <Services/>
                <Footer/>
            </main>
        </>
    );
}

export default Home;
